// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace MolesTest
{
    public partial class Y2KCheckerTest
    {
[TestMethod]
[PexGeneratedBy(typeof(Y2KCheckerTest))]
[HostType("Moles")]
public void Check575()
{
    this.Check(default(DateTime));
}
[TestMethod]
[PexGeneratedBy(typeof(Y2KCheckerTest))]
[ExpectedException(typeof(ApplicationException))]
[HostType("Moles")]
public void CheckThrowsApplicationException143()
{
    this.Check(new DateTime(4611686018427387903L & 630822816000000000L, 
                            (DateTimeKind)(630822816000000000uL >> 62)));
}
    }
}
